### PR TITLE
Add JavaScript webpack test app

### PR DESCRIPTION
**Pull request by tombruijn**
Add basic JavaScript app that uses webpack to precompile the JavaScript
app.

Use the JavaScript integration along with the webpack plugin to send
private sourcemaps for the app.

It's a little non standard setup, but I cannot wait for the container to
restart when running the server in `boot.sh`. It takes 10+ minutes on my
machine to build all the integrations, link them and start the server.
So I split it up and used the `console.sh` command to run the server.
Not ideal, but good enough for now to test it.

### CODE REVIEW

**Review by thijsc — APPROVED** [review]
Great that we can test this now. I'll see if I can come up with a nicer way to handle this scenario in the test setup.

**Comment by tombruijn** [comment]
> I'll see if I can come up with a nicer way to handle this scenario in the test setup.

What do you mean? The thing I did with the `console` command? I'm also thinking about specifying commands like this instead: `rake javascript/webpack command=up/build/console/bash`

**Comment by tombruijn** [comment]
> I'll see if I can come up with a nicer way to handle this scenario in the test setup.

@thijsc What do you mean? The thing I did with the `console` command? I'm also thinking about specifying commands like this instead: `rake app=javascript/webpack command=up/build/console/bash`

**Comment by thijsc** [comment]
> @thijsc What do you mean? The thing I did with the `console` command? I'm also thinking about specifying commands like this instead: `rake app=javascript/webpack command=up/build/console/bash`

Yes. It should't be necessary to go outside of the normal flow, so we should improve the normal flow to take away this pain.

**Comment by tombruijn** [comment]
@thijsc the main reason for me to go this flow is that the normal flow is _extremely slow_. Building and linking the integration takes 10 minutes roughly. It makes development very unproductive. I'm not going to go through that every time. The `yarn build` command isn't setting any speed records on the host, but I think the problem is amplified on docker, probably because it's all in a mounted volume.

**Comment by thijsc** [comment]
> @thijsc the main reason for me to go this flow is that the normal flow is _extremely slow_. Building and linking the integration takes ~10 minutes roughly~ 16 minutes. It makes development very unproductive. I'm not going to go through that every time. The `yarn build` command isn't setting any speed records on the host, but I think the problem is amplified on docker, probably because it's all in a mounted volume.

Understood. I'll spend some time on trying to come up with a structure so that the standard approach works and is also fast. Maybe by wrapping the server command in something that can reboot it.

**Comment by tombruijn** [comment]
I also wonder if we should use NFS volumes instead to improve performance a bit: https://www.jeffgeerling.com/blog/2020/revisiting-docker-macs-performance-nfs-volumes

Anyway, I'll merge this as is right now. At least we have a test app.

**Pull request merged**
