### PR TITLE
Add Rails6 + MySQL test application

### PR DESCRIPTION
**Pull request by luismiramirez**
This new app uses Rails6 + MySQL as the DB adapter. It follows the
current test setup schema.

Part of: https://github.com/appsignal/integration-guide/issues/63

### CODE REVIEW

**Comment by tombruijn** [comment]
I'm unable to run the migrations for this app for some reason. I've tried upgrading the listen and rb-inotify gems, but no luck.

<details>
<summary>Click me to expand error</summary>

```
$ bin/rails db:migrate
rails aborted!
Errno::ENOSYS: Function not implemented - Failed to initialize inotify
/app/vendor/bundle/ruby/3.1.0/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:69:in `initialize'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/adapter/linux.rb:29:in `new'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/adapter/linux.rb:29:in `_configure'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/adapter/base.rb:47:in `block in configure'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/adapter/base.rb:42:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/adapter/base.rb:42:in `configure'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/adapter/base.rb:66:in `start'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:71:in `block in <class:Listener>'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `instance_eval'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:124:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:105:in `transition_with_callbacks!'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/fsm.rb:72:in `transition'
/app/vendor/bundle/ruby/3.1.0/gems/listen-3.7.1/lib/listen/listener.rb:92:in `start'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/evented_file_update_checker.rb:109:in `start'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/evented_file_update_checker.rb:88:in `initialize'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/evented_file_update_checker.rb:44:in `new'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/evented_file_update_checker.rb:44:in `initialize'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/i18n_railtie.rb:64:in `new'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/i18n_railtie.rb:64:in `initialize_i18n'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/i18n_railtie.rb:20:in `block in <class:Railtie>'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/application/finisher.rb:140:in `block in <module:Finisher>'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/application.rb:391:in `initialize!'
/app/config/environment.rb:5:in `<main>'
/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/application.rb:367:in `require_environment!'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/command.rb:50:in `invoke'
/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.4.6/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```
</details>

**Comment by luismiramirez** [comment]
@tombruijn does it work now with the platform specified? I'm not able to get that error

**Comment by tombruijn** [comment]
No this is after I've fixed the platform issue otherwise I can't run it at all.

**Comment by luismiramirez** [comment]
@tombruijn I applied the workaround proposed here https://github.com/evilmartians/terraforming-rails/issues/34.

The latest version should work for you.

**Review by tombruijn — APPROVED** [review]
Works for me! What did you change, because I can't see what you changed exactly and the `file_watcher` is not configured?

**Comment by luismiramirez** [comment]
@tombruijn I commented the `file_watcher` option in the last force push

**Pull request merged**
