### PR TITLE
Add new Next.js app

### PR DESCRIPTION
**Pull request by tombruijn**
This uses the App Router, but that's the default now, so no config needed like in `nextjs-appdir`.

This app more closely resembles a new Next.js app. The one a user in support is having issues with.

Add a system to choose to run the Next.js production mode instead of the development mode without needing a whole new app, using Docker build args.

### CODE REVIEW

**Review by unflxw — APPROVED** [review]
I'm still not quite sure what the difference is between this and the existing `nextjs-appdir`. I'm happy to add this one, but if this is in practice an updated version of the existing `nextjs-appdir`, then maybe we should also remove `nextjs-appdir` as part of this PR.

**Comment by unflxw** [comment]
I really like the passing of build args trick, that could be useful for other test setups as well. 💯

**Comment by tombruijn** [comment]
The `nextjs-appdir` is an older version of the next.js app where the app router was only an experimental config option. If we don't care for that setup anymore for that specific version, I'm okay with removing it.

**Comment by unflxw** [comment]
Let's remove it then. 👍

**Pull request merged**
